name: attendance

services:
  postgres:
    restart: unless-stopped
    container_name: attendance_postgres
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
  attendance-system:
    restart: unless-stopped
    container_name: attendance
    image: ghcr.io/team3132/attendance:${TAG:-latest}
    ports:
      - 1420:1420
    links:
      - postgres
    environment:
      - TZ=Australia/Sydney
      - DATABASE_URL
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - DISCORD_CALLBACK_URL
      - DISCORD_TOKEN
      - DISCORD_PUBLIC_KEY
      - GUILD_ID
      - VITE_URL
      - GOOGLE_CLIENT_EMAIL
      - GOOGLE_PRIVATE_KEY
      - GOOGLE_CALENDAR_ID
      - ADMIN_ROLE_ID
  metabase:
    image: metabase metabase/metabase
    container_name: metabase
    ports:
      - 3030:3000
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - /dev/urandom:/dev/random:ro
      - metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
volumes:
  postgres-data:
  metabase-data:
