/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiWsRouteImport } from './routes/api/ws'
import { Route as ApiInteractionRouteImport } from './routes/api/interaction'
import { Route as AuthenticatedUpdateRouteImport } from './routes/_authenticated/update'
import { Route as AuthenticatedProfileRouteRouteImport } from './routes/_authenticated/profile/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin_/route'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin_/index'
import { Route as ApiAuthDiscordRouteImport } from './routes/api/auth.discord'
import { Route as AuthenticatedProfileSessionsRouteImport } from './routes/_authenticated/profile/sessions'
import { Route as AuthenticatedProfilePendingRouteImport } from './routes/_authenticated/profile/pending'
import { Route as AuthenticatedEventsEventIdRouteRouteImport } from './routes/_authenticated/events.$eventId/route'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin_/users/index'
import { Route as AuthenticatedAdminEventParsingIndexRouteImport } from './routes/_authenticated/admin_/event-parsing/index'
import { Route as ApiSchedulerCalendarTriggerRouteImport } from './routes/api/scheduler.calendar.trigger'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth.discord.callback'
import { Route as AuthenticatedEventsEventIdQrCodeRouteImport } from './routes/_authenticated/events.$eventId/qr-code'
import { Route as AuthenticatedEventsEventIdCheckInRouteImport } from './routes/_authenticated/events.$eventId/check-in'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin_/users/$userId'
import { Route as AuthenticatedAdminEventParsingCreateRouteImport } from './routes/_authenticated/admin_/event-parsing/create'
import { Route as AuthenticatedAdminEventParsingRuleIdRouteImport } from './routes/_authenticated/admin_/event-parsing/$ruleId'
import { Route as AuthenticatedEventsEventIdRsvpsRouteRouteImport } from './routes/_authenticated/events.$eventId/rsvps/route'
import { Route as AuthenticatedAdminUsersUserIdIndexRouteImport } from './routes/_authenticated/admin_/users/$userId/index'
import { Route as AuthenticatedEventsEventIdRsvpsNewRouteImport } from './routes/_authenticated/events.$eventId/rsvps/new'
import { Route as AuthenticatedAdminUsersUserIdSessionsRouteImport } from './routes/_authenticated/admin_/users/$userId/sessions'
import { Route as AuthenticatedAdminUsersUserIdPendingRouteImport } from './routes/_authenticated/admin_/users/$userId/pending'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWsRoute = ApiWsRouteImport.update({
  id: '/api/ws',
  path: '/api/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInteractionRoute = ApiInteractionRouteImport.update({
  id: '/api/interaction',
  path: '/api/interaction',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpdateRoute = AuthenticatedUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRouteRoute =
  AuthenticatedProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin_',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiAuthDiscordRoute = ApiAuthDiscordRouteImport.update({
  id: '/api/auth/discord',
  path: '/api/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileSessionsRoute =
  AuthenticatedProfileSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedProfileRouteRoute,
  } as any)
const AuthenticatedProfilePendingRoute =
  AuthenticatedProfilePendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedProfileRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRouteRoute =
  AuthenticatedEventsEventIdRouteRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventParsingIndexRoute =
  AuthenticatedAdminEventParsingIndexRouteImport.update({
    id: '/event-parsing/',
    path: '/event-parsing/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiSchedulerCalendarTriggerRoute =
  ApiSchedulerCalendarTriggerRouteImport.update({
    id: '/api/scheduler/calendar/trigger',
    path: '/api/scheduler/calendar/trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthDiscordRoute,
} as any)
const AuthenticatedEventsEventIdQrCodeRoute =
  AuthenticatedEventsEventIdQrCodeRouteImport.update({
    id: '/qr-code',
    path: '/qr-code',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdCheckInRoute =
  AuthenticatedEventsEventIdCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventParsingCreateRoute =
  AuthenticatedAdminEventParsingCreateRouteImport.update({
    id: '/event-parsing/create',
    path: '/event-parsing/create',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventParsingRuleIdRoute =
  AuthenticatedAdminEventParsingRuleIdRouteImport.update({
    id: '/event-parsing/$ruleId',
    path: '/event-parsing/$ruleId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRsvpsRouteRoute =
  AuthenticatedEventsEventIdRsvpsRouteRouteImport.update({
    id: '/rsvps',
    path: '/rsvps',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdIndexRoute =
  AuthenticatedAdminUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)
const AuthenticatedEventsEventIdRsvpsNewRoute =
  AuthenticatedEventsEventIdRsvpsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedEventsEventIdRsvpsRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdSessionsRoute =
  AuthenticatedAdminUsersUserIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)
const AuthenticatedAdminUsersUserIdPendingRoute =
  AuthenticatedAdminUsersUserIdPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/profile': typeof AuthenticatedProfileRouteRouteWithChildren
  '/update': typeof AuthenticatedUpdateRoute
  '/api/interaction': typeof ApiInteractionRoute
  '/api/ws': typeof ApiWsRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRouteRouteWithChildren
  '/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/profile/sessions': typeof AuthenticatedProfileSessionsRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/events/$eventId/rsvps': typeof AuthenticatedEventsEventIdRsvpsRouteRouteWithChildren
  '/admin/event-parsing/$ruleId': typeof AuthenticatedAdminEventParsingRuleIdRoute
  '/admin/event-parsing/create': typeof AuthenticatedAdminEventParsingCreateRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  '/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/scheduler/calendar/trigger': typeof ApiSchedulerCalendarTriggerRoute
  '/admin/event-parsing/': typeof AuthenticatedAdminEventParsingIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/admin/users/$userId/sessions': typeof AuthenticatedAdminUsersUserIdSessionsRoute
  '/events/$eventId/rsvps/new': typeof AuthenticatedEventsEventIdRsvpsNewRoute
  '/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/update': typeof AuthenticatedUpdateRoute
  '/api/interaction': typeof ApiInteractionRoute
  '/api/ws': typeof ApiWsRoute
  '/': typeof AuthenticatedIndexRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRouteRouteWithChildren
  '/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/profile/sessions': typeof AuthenticatedProfileSessionsRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/events/$eventId/rsvps': typeof AuthenticatedEventsEventIdRsvpsRouteRouteWithChildren
  '/admin/event-parsing/$ruleId': typeof AuthenticatedAdminEventParsingRuleIdRoute
  '/admin/event-parsing/create': typeof AuthenticatedAdminEventParsingCreateRoute
  '/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/scheduler/calendar/trigger': typeof ApiSchedulerCalendarTriggerRoute
  '/admin/event-parsing': typeof AuthenticatedAdminEventParsingIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/admin/users/$userId/sessions': typeof AuthenticatedAdminUsersUserIdSessionsRoute
  '/events/$eventId/rsvps/new': typeof AuthenticatedEventsEventIdRsvpsNewRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin_': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRouteRouteWithChildren
  '/_authenticated/update': typeof AuthenticatedUpdateRoute
  '/api/interaction': typeof ApiInteractionRoute
  '/api/ws': typeof ApiWsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRouteRouteWithChildren
  '/_authenticated/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/_authenticated/profile/sessions': typeof AuthenticatedProfileSessionsRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/_authenticated/admin_/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/events/$eventId/rsvps': typeof AuthenticatedEventsEventIdRsvpsRouteRouteWithChildren
  '/_authenticated/admin_/event-parsing/$ruleId': typeof AuthenticatedAdminEventParsingRuleIdRoute
  '/_authenticated/admin_/event-parsing/create': typeof AuthenticatedAdminEventParsingCreateRoute
  '/_authenticated/admin_/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  '/_authenticated/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/_authenticated/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/scheduler/calendar/trigger': typeof ApiSchedulerCalendarTriggerRoute
  '/_authenticated/admin_/event-parsing/': typeof AuthenticatedAdminEventParsingIndexRoute
  '/_authenticated/admin_/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/admin_/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/_authenticated/admin_/users/$userId/sessions': typeof AuthenticatedAdminUsersUserIdSessionsRoute
  '/_authenticated/events/$eventId/rsvps/new': typeof AuthenticatedEventsEventIdRsvpsNewRoute
  '/_authenticated/admin_/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/login'
    | '/admin'
    | '/profile'
    | '/update'
    | '/api/interaction'
    | '/api/ws'
    | '/events/$eventId'
    | '/profile/pending'
    | '/profile/sessions'
    | '/api/auth/discord'
    | '/admin/'
    | '/profile/'
    | '/events/$eventId/rsvps'
    | '/admin/event-parsing/$ruleId'
    | '/admin/event-parsing/create'
    | '/admin/users/$userId'
    | '/events/$eventId/check-in'
    | '/events/$eventId/qr-code'
    | '/api/auth/discord/callback'
    | '/api/scheduler/calendar/trigger'
    | '/admin/event-parsing/'
    | '/admin/users/'
    | '/admin/users/$userId/pending'
    | '/admin/users/$userId/sessions'
    | '/events/$eventId/rsvps/new'
    | '/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/login'
    | '/update'
    | '/api/interaction'
    | '/api/ws'
    | '/'
    | '/events/$eventId'
    | '/profile/pending'
    | '/profile/sessions'
    | '/api/auth/discord'
    | '/admin'
    | '/profile'
    | '/events/$eventId/rsvps'
    | '/admin/event-parsing/$ruleId'
    | '/admin/event-parsing/create'
    | '/events/$eventId/check-in'
    | '/events/$eventId/qr-code'
    | '/api/auth/discord/callback'
    | '/api/scheduler/calendar/trigger'
    | '/admin/event-parsing'
    | '/admin/users'
    | '/admin/users/$userId/pending'
    | '/admin/users/$userId/sessions'
    | '/events/$eventId/rsvps/new'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/error'
    | '/login'
    | '/_authenticated/admin_'
    | '/_authenticated/profile'
    | '/_authenticated/update'
    | '/api/interaction'
    | '/api/ws'
    | '/_authenticated/'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/profile/pending'
    | '/_authenticated/profile/sessions'
    | '/api/auth/discord'
    | '/_authenticated/admin_/'
    | '/_authenticated/profile/'
    | '/_authenticated/events/$eventId/rsvps'
    | '/_authenticated/admin_/event-parsing/$ruleId'
    | '/_authenticated/admin_/event-parsing/create'
    | '/_authenticated/admin_/users/$userId'
    | '/_authenticated/events/$eventId/check-in'
    | '/_authenticated/events/$eventId/qr-code'
    | '/api/auth/discord/callback'
    | '/api/scheduler/calendar/trigger'
    | '/_authenticated/admin_/event-parsing/'
    | '/_authenticated/admin_/users/'
    | '/_authenticated/admin_/users/$userId/pending'
    | '/_authenticated/admin_/users/$userId/sessions'
    | '/_authenticated/events/$eventId/rsvps/new'
    | '/_authenticated/admin_/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  ApiInteractionRoute: typeof ApiInteractionRoute
  ApiWsRoute: typeof ApiWsRoute
  ApiAuthDiscordRoute: typeof ApiAuthDiscordRouteWithChildren
  ApiSchedulerCalendarTriggerRoute: typeof ApiSchedulerCalendarTriggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ws': {
      id: '/api/ws'
      path: '/api/ws'
      fullPath: '/api/ws'
      preLoaderRoute: typeof ApiWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interaction': {
      id: '/api/interaction'
      path: '/api/interaction'
      fullPath: '/api/interaction'
      preLoaderRoute: typeof ApiInteractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/update': {
      id: '/_authenticated/update'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof AuthenticatedUpdateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_': {
      id: '/_authenticated/admin_'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRouteRoute
    }
    '/_authenticated/admin_/': {
      id: '/_authenticated/admin_/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/auth/discord': {
      id: '/api/auth/discord'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord'
      preLoaderRoute: typeof ApiAuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/sessions': {
      id: '/_authenticated/profile/sessions'
      path: '/sessions'
      fullPath: '/profile/sessions'
      preLoaderRoute: typeof AuthenticatedProfileSessionsRouteImport
      parentRoute: typeof AuthenticatedProfileRouteRoute
    }
    '/_authenticated/profile/pending': {
      id: '/_authenticated/profile/pending'
      path: '/pending'
      fullPath: '/profile/pending'
      preLoaderRoute: typeof AuthenticatedProfilePendingRouteImport
      parentRoute: typeof AuthenticatedProfileRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/users/': {
      id: '/_authenticated/admin_/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin_/event-parsing/': {
      id: '/_authenticated/admin_/event-parsing/'
      path: '/event-parsing'
      fullPath: '/admin/event-parsing/'
      preLoaderRoute: typeof AuthenticatedAdminEventParsingIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/scheduler/calendar/trigger': {
      id: '/api/scheduler/calendar/trigger'
      path: '/api/scheduler/calendar/trigger'
      fullPath: '/api/scheduler/calendar/trigger'
      preLoaderRoute: typeof ApiSchedulerCalendarTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof ApiAuthDiscordRoute
    }
    '/_authenticated/events/$eventId/qr-code': {
      id: '/_authenticated/events/$eventId/qr-code'
      path: '/qr-code'
      fullPath: '/events/$eventId/qr-code'
      preLoaderRoute: typeof AuthenticatedEventsEventIdQrCodeRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/check-in': {
      id: '/_authenticated/events/$eventId/check-in'
      path: '/check-in'
      fullPath: '/events/$eventId/check-in'
      preLoaderRoute: typeof AuthenticatedEventsEventIdCheckInRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/admin_/users/$userId': {
      id: '/_authenticated/admin_/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin_/event-parsing/create': {
      id: '/_authenticated/admin_/event-parsing/create'
      path: '/event-parsing/create'
      fullPath: '/admin/event-parsing/create'
      preLoaderRoute: typeof AuthenticatedAdminEventParsingCreateRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin_/event-parsing/$ruleId': {
      id: '/_authenticated/admin_/event-parsing/$ruleId'
      path: '/event-parsing/$ruleId'
      fullPath: '/admin/event-parsing/$ruleId'
      preLoaderRoute: typeof AuthenticatedAdminEventParsingRuleIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/events/$eventId/rsvps': {
      id: '/_authenticated/events/$eventId/rsvps'
      path: '/rsvps'
      fullPath: '/events/$eventId/rsvps'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRsvpsRouteRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/admin_/users/$userId/': {
      id: '/_authenticated/admin_/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRoute
    }
    '/_authenticated/events/$eventId/rsvps/new': {
      id: '/_authenticated/events/$eventId/rsvps/new'
      path: '/new'
      fullPath: '/events/$eventId/rsvps/new'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRsvpsNewRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRsvpsRouteRoute
    }
    '/_authenticated/admin_/users/$userId/sessions': {
      id: '/_authenticated/admin_/users/$userId/sessions'
      path: '/sessions'
      fullPath: '/admin/users/$userId/sessions'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRoute
    }
    '/_authenticated/admin_/users/$userId/pending': {
      id: '/_authenticated/admin_/users/$userId/pending'
      path: '/pending'
      fullPath: '/admin/users/$userId/pending'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdPendingRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRoute
    }
  }
}

interface AuthenticatedAdminUsersUserIdRouteChildren {
  AuthenticatedAdminUsersUserIdPendingRoute: typeof AuthenticatedAdminUsersUserIdPendingRoute
  AuthenticatedAdminUsersUserIdSessionsRoute: typeof AuthenticatedAdminUsersUserIdSessionsRoute
  AuthenticatedAdminUsersUserIdIndexRoute: typeof AuthenticatedAdminUsersUserIdIndexRoute
}

const AuthenticatedAdminUsersUserIdRouteChildren: AuthenticatedAdminUsersUserIdRouteChildren =
  {
    AuthenticatedAdminUsersUserIdPendingRoute:
      AuthenticatedAdminUsersUserIdPendingRoute,
    AuthenticatedAdminUsersUserIdSessionsRoute:
      AuthenticatedAdminUsersUserIdSessionsRoute,
    AuthenticatedAdminUsersUserIdIndexRoute:
      AuthenticatedAdminUsersUserIdIndexRoute,
  }

const AuthenticatedAdminUsersUserIdRouteWithChildren =
  AuthenticatedAdminUsersUserIdRoute._addFileChildren(
    AuthenticatedAdminUsersUserIdRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventParsingRuleIdRoute: typeof AuthenticatedAdminEventParsingRuleIdRoute
  AuthenticatedAdminEventParsingCreateRoute: typeof AuthenticatedAdminEventParsingCreateRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  AuthenticatedAdminEventParsingIndexRoute: typeof AuthenticatedAdminEventParsingIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminEventParsingRuleIdRoute:
      AuthenticatedAdminEventParsingRuleIdRoute,
    AuthenticatedAdminEventParsingCreateRoute:
      AuthenticatedAdminEventParsingCreateRoute,
    AuthenticatedAdminUsersUserIdRoute:
      AuthenticatedAdminUsersUserIdRouteWithChildren,
    AuthenticatedAdminEventParsingIndexRoute:
      AuthenticatedAdminEventParsingIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedProfileRouteRouteChildren {
  AuthenticatedProfilePendingRoute: typeof AuthenticatedProfilePendingRoute
  AuthenticatedProfileSessionsRoute: typeof AuthenticatedProfileSessionsRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteRouteChildren: AuthenticatedProfileRouteRouteChildren =
  {
    AuthenticatedProfilePendingRoute: AuthenticatedProfilePendingRoute,
    AuthenticatedProfileSessionsRoute: AuthenticatedProfileSessionsRoute,
    AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  }

const AuthenticatedProfileRouteRouteWithChildren =
  AuthenticatedProfileRouteRoute._addFileChildren(
    AuthenticatedProfileRouteRouteChildren,
  )

interface AuthenticatedEventsEventIdRsvpsRouteRouteChildren {
  AuthenticatedEventsEventIdRsvpsNewRoute: typeof AuthenticatedEventsEventIdRsvpsNewRoute
}

const AuthenticatedEventsEventIdRsvpsRouteRouteChildren: AuthenticatedEventsEventIdRsvpsRouteRouteChildren =
  {
    AuthenticatedEventsEventIdRsvpsNewRoute:
      AuthenticatedEventsEventIdRsvpsNewRoute,
  }

const AuthenticatedEventsEventIdRsvpsRouteRouteWithChildren =
  AuthenticatedEventsEventIdRsvpsRouteRoute._addFileChildren(
    AuthenticatedEventsEventIdRsvpsRouteRouteChildren,
  )

interface AuthenticatedEventsEventIdRouteRouteChildren {
  AuthenticatedEventsEventIdRsvpsRouteRoute: typeof AuthenticatedEventsEventIdRsvpsRouteRouteWithChildren
  AuthenticatedEventsEventIdCheckInRoute: typeof AuthenticatedEventsEventIdCheckInRoute
  AuthenticatedEventsEventIdQrCodeRoute: typeof AuthenticatedEventsEventIdQrCodeRoute
}

const AuthenticatedEventsEventIdRouteRouteChildren: AuthenticatedEventsEventIdRouteRouteChildren =
  {
    AuthenticatedEventsEventIdRsvpsRouteRoute:
      AuthenticatedEventsEventIdRsvpsRouteRouteWithChildren,
    AuthenticatedEventsEventIdCheckInRoute:
      AuthenticatedEventsEventIdCheckInRoute,
    AuthenticatedEventsEventIdQrCodeRoute:
      AuthenticatedEventsEventIdQrCodeRoute,
  }

const AuthenticatedEventsEventIdRouteRouteWithChildren =
  AuthenticatedEventsEventIdRouteRoute._addFileChildren(
    AuthenticatedEventsEventIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedProfileRouteRoute: typeof AuthenticatedProfileRouteRouteWithChildren
  AuthenticatedUpdateRoute: typeof AuthenticatedUpdateRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEventsEventIdRouteRoute: typeof AuthenticatedEventsEventIdRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedProfileRouteRoute: AuthenticatedProfileRouteRouteWithChildren,
  AuthenticatedUpdateRoute: AuthenticatedUpdateRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEventsEventIdRouteRoute:
    AuthenticatedEventsEventIdRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiAuthDiscordRouteChildren {
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
}

const ApiAuthDiscordRouteChildren: ApiAuthDiscordRouteChildren = {
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
}

const ApiAuthDiscordRouteWithChildren = ApiAuthDiscordRoute._addFileChildren(
  ApiAuthDiscordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  ApiInteractionRoute: ApiInteractionRoute,
  ApiWsRoute: ApiWsRoute,
  ApiAuthDiscordRoute: ApiAuthDiscordRouteWithChildren,
  ApiSchedulerCalendarTriggerRoute: ApiSchedulerCalendarTriggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
